namespace: staging
replicas:
  - name: nginx-deployment
    count: 1
images:
  - name: mwinel/nginx-devops-lesson
    newTag: v0.1.0
resources:
  - ../../../base
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: dockerconfigjson }]
